# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import user_pb2 as user__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateNewUser = channel.unary_unary(
                '/User/CreateNewUser',
                request_serializer=user__pb2.SignupData.SerializeToString,
                response_deserializer=user__pb2.Response.FromString,
                )
        self.UserSignin = channel.unary_unary(
                '/User/UserSignin',
                request_serializer=user__pb2.SigninData.SerializeToString,
                response_deserializer=user__pb2.Response.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file"""

    def CreateNewUser(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserSignin(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateNewUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNewUser,
                    request_deserializer=user__pb2.SignupData.FromString,
                    response_serializer=user__pb2.Response.SerializeToString,
            ),
            'UserSignin': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSignin,
                    request_deserializer=user__pb2.SigninData.FromString,
                    response_serializer=user__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def CreateNewUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/User/CreateNewUser',
            user__pb2.SignupData.SerializeToString,
            user__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UserSignin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/User/UserSignin',
            user__pb2.SigninData.SerializeToString,
            user__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
